### PR TITLE
added Manan Varma readme.md

### PR DESCRIPTION
**Pull request by MAnonInfinity**
## Your Username
MAnonInfinity

## What Changes you had made?
Added customized readme.md

## Issue ID( if any )
Example - #30

## Additional Description (Optional)
Any Additional Information? Add Here

### CODE REVIEW

**Comment by neeraj15022001** [comment]
@MAnonInfinity 
- [ ] change the repository name to your github username

**Comment by victor-thescuti** [comment]
please change file name from readme.md to README.md

**Review by victor-thescuti — COMMENTED** [review]
chnage file name to README.md from readme.md

**Review by victor-thescuti — CHANGES_REQUESTED** [review]
change filename to README.md from readme.md

**Review by neeraj15022001 — APPROVED** [review]

**Review by neeraj15022001 — APPROVED** [review]

**Review by victor-thescuti — APPROVED** [review]

**Comment by victor-thescuti** [comment]
Great Work @MAnonInfinity. Thanks for contributing!!!!

**Comment by MAnonInfinity** [comment]
My pleasure @victor-thescuti!!

**Pull request merged**
